options:
  install-sources:
    type: string
    description: Package sources for install
  install-keys:
    type: string
    description: Apt keys for package install sources
  heat-plugin-path:
    type: string
    description: Path to directory where heat looks for plugins
    default: /usr/lib/heat
